Repository GSG-G11/Memory-Game, pull requests merged in 2022-04, with the labels that each got.

#2 Create Files #1
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: Done

#5 Create Memory Card #3
  package-lock.json
  package.json
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/components/MemoryCard.jsx
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: Approved

#6 create card component
  package.json
  public/favicon.ico
  src/App.js
  src/components/card.jsx
  src/index.js
Labels: Approved

#8 Fix Some Code #7
  package.json
  public/favicon.ico
  src/App.css
  src/App.js
  src/assets/backCard.png
  src/assets/index.js
  src/assets/pair1.jpg
  src/assets/pair2.jpg
  src/assets/pair3.jpg
  src/assets/pair4.jpg
  src/assets/pair5.jpg
  src/assets/pair6.jpg
  src/assets/pair7.jpg
  src/assets/pair8.jpg
  src/components/MemoryCard.jsx
  src/components/card.jsx
Labels: Approved

#13 Create StartGame #10
  public/manifest.json
  src/App.js
  src/components/GameBoard.jsx
  src/components/StarGame.jsx
Labels: Approved

#15 Create GameBoard #9
  README.md
  public/index.html
  src/App.css
  src/App.js
  src/assets/index.js
  src/components/MemoryCard.jsx
  src/components/PlayAgain.jsx
  src/index.js
Labels: Awaiting Review
